import firebase from '@react-native-firebase/app';
import React, { FunctionComponent, useEffect, useRef } from 'react';
import { AppState } from 'react-native';
import Braze from 'react-native-appboy-sdk';
import { API_URL } from 'react-native-dotenv';
import SplashScreen from 'react-native-splash-screen';
import { useDispatch, useSelector } from 'react-redux';
import styled from 'styled-components/native';

import DebugMenu from './components/DebugMenu';
import DialogStack from './components/dialogs/DialogStack';
import ServerSelector from './components/ServerSelector';
import { getServerConfig, isServerConfiguration } from './config/server';
import useDidMount from './hooks/useDidMount';
import useI18n from './hooks/useI18n';
import useIdentifyUser from './hooks/useIdentifyUser';
import useServer from './hooks/useServer';
import useTranslations from './hooks/useTranslations';
import AuthStack from './navigation/AuthStack';
import RootNavigation from './navigation/RootNavigation';
import { default as PlatformAnalyticsModule } from './packages/platformAnalytics';
import { activityControllerActions } from './redux/slices/ActivityControllerSlice';
import { authActions } from './redux/slices/authSlice';
import { selectAuthState, selectIsLoading } from './redux/slices/authSlice/selectors';
import { imageActions } from './redux/slices/imageSlice';
import { serverActions } from './redux/slices/serverSlice';
import { selectIsServerInitialized, selectServer } from './redux/slices/serverSlice/selectors';
import platformAnalytics from './services/analytics/platformAnalytics';
import { Doorman } from './services/doorman';
import { getStatusBarHeight, isProdBuild } from './services/helpers';
import { fetchImages } from './services/images';
import { isSelfCare } from './services/program';
import { getItem } from './services/storage';
import { selectIsHome, selectIsInFullScreen } from '@src/redux/slices/statusBarSlice/selectors';
